#ifndef _ERRORS
#define _ERRORS

enum errors{
	NO_ERRORS,
	CAN_NOT_OPEN_FILE, 
	NULL_MEMBERS_MORE_THEN_ANOTHER, 
	NEGATIVE_PARAMETER_VALUE, 
	CAN_NOT_ALLOCATE_MEMORY, 
	NOT_ENOUGH_PARAMETERS 
};

#endif